/etc/alternatives/mutt
/var/cache/apt/archives/mutt_1.5.21-6.2+deb7u3_armhf.deb
/var/lib/menu-xdg/applications/menu-xdg/X-Debian-Applications-Network-Communication-mutt.desktop
/var/lib/dpkg/alternatives/mutt
/var/lib/dpkg/info/mutt.postinst
/var/lib/dpkg/info/mutt.preinst
/var/lib/dpkg/info/mutt.conffiles
/var/lib/dpkg/info/mutt.postrm
/var/lib/dpkg/info/mutt.prerm
/var/lib/dpkg/info/mutt.list
/var/lib/dpkg/info/mutt.md5sums
/home/pi/mutt.m
/home/pi/.muttrc
/usr/bin/mutt
/usr/bin/mutt-org
/usr/bin/mutt_dotlock
/usr/share/vim/vim73/syntax/muttrc.vim
/usr/share/vim/vim73/ftplugin/muttrc.vim
/usr/share/nano/mutt.nanorc
/usr/share/bash-completion/completions/mutt
/usr/share/bash-completion/completions/muttng
/usr/share/applications/mutt.desktop
/usr/share/lintian/overrides/mutt
/usr/share/dictionaries-common/mutt-ispell-init
/usr/share/doc-base/mutt
/usr/share/menu/mutt
/usr/share/bug/mutt
/usr/share/bug/mutt/script
/usr/share/bug/mutt/control
/usr/share/xfce4/helpers/muttng.desktop
/usr/share/xfce4/helpers/mutt.desktop
/usr/share/doc/mutt
/usr/share/doc/mutt/PGP-Notes.txt.gz
/usr/share/doc/mutt/README.Debian
/usr/share/doc/mutt/README.SECURITY
/usr/share/doc/mutt/README
/usr/share/doc/mutt/NEWS.old.gz
/usr/share/doc/mutt/changelog.gz
/usr/share/doc/mutt/TODO
/usr/share/doc/mutt/manual.txt.gz
/usr/share/doc/mutt/NEWS.Debian.gz
/usr/share/doc/mutt/changelog.Debian.gz
/usr/share/doc/mutt/copyright
/usr/share/doc/mutt/README.Patches
/usr/share/doc/mutt/NEWS.gz
/usr/share/doc/mutt/examples
/usr/share/doc/mutt/examples/smime_keys_test.pl
/usr/share/doc/mutt/examples/gpg.rc
/usr/share/doc/mutt/examples/colors.linux
/usr/share/doc/mutt/examples/colors.default
/usr/share/doc/mutt/examples/Tin.rc
/usr/share/doc/mutt/examples/ray.muttrc
/usr/share/doc/mutt/examples/Muttrc.gz
/usr/share/doc/mutt/examples/pgp5.rc
/usr/share/doc/mutt/examples/sample.mailcap
/usr/share/doc/mutt/examples/colors.angdraug.gz
/usr/share/doc/mutt/examples/pgp6.rc
/usr/share/doc/mutt/examples/mutt_xtitle
/usr/share/doc/mutt/examples/sample.muttrc.gz
/usr/share/doc/mutt/examples/Mush.rc
/usr/share/doc/mutt/examples/sample.muttrc-tlr.gz
/usr/share/doc/mutt/examples/sidebar.muttrc
/usr/share/doc/mutt/examples/pgp2.rc
/usr/share/doc/mutt/examples/Pine.rc
/usr/share/doc/mutt/examples/smime.rc
/usr/share/doc/mutt/README.SSL.gz
/usr/share/doc/mutt/README.SMIME
/usr/share/doc/mutt/html
/usr/share/doc/mutt/html/mimesupport.html
/usr/share/doc/mutt/html/tuning.html
/usr/share/doc/mutt/html/index.html
/usr/share/doc/mutt/html/intro.html
/usr/share/doc/mutt/html/optionalfeatures.html
/usr/share/doc/mutt/html/advancedusage.html
/usr/share/doc/mutt/html/configuration.html
/usr/share/doc/mutt/html/gettingstarted.html
/usr/share/doc/mutt/html/manual.html
/usr/share/doc/mutt/html/security.html
/usr/share/doc/mutt/html/miscellany.html
/usr/share/doc/mutt/html/reference.html
/usr/share/doc/dovecot-core/dovecot/wiki/mutt.txt
/usr/share/doc/spamassassin/examples/muttrc
/usr/share/pixmaps/mutt.xpm
/usr/share/man/man1/mutt_dotlock.1.gz
/usr/share/man/man1/mutt.1.gz
/usr/share/man/man5/muttrc.5.gz
/usr/share/locale/ru/LC_MESSAGES/mutt.mo
/usr/share/locale/sv/LC_MESSAGES/mutt.mo
/usr/share/locale/nl/LC_MESSAGES/mutt.mo
/usr/share/locale/sk/LC_MESSAGES/mutt.mo
/usr/share/locale/el/LC_MESSAGES/mutt.mo
/usr/share/locale/lt/LC_MESSAGES/mutt.mo
/usr/share/locale/tr/LC_MESSAGES/mutt.mo
/usr/share/locale/gl/LC_MESSAGES/mutt.mo
/usr/share/locale/id/LC_MESSAGES/mutt.mo
/usr/share/locale/de/LC_MESSAGES/mutt.mo
/usr/share/locale/zh_TW/LC_MESSAGES/mutt.mo
/usr/share/locale/hu/LC_MESSAGES/mutt.mo
/usr/share/locale/es/LC_MESSAGES/mutt.mo
/usr/share/locale/zh_CN/LC_MESSAGES/mutt.mo
/usr/share/locale/pl/LC_MESSAGES/mutt.mo
/usr/share/locale/da/LC_MESSAGES/mutt.mo
/usr/share/locale/ko/LC_MESSAGES/mutt.mo
/usr/share/locale/it/LC_MESSAGES/mutt.mo
/usr/share/locale/fr/LC_MESSAGES/mutt.mo
/usr/share/locale/pt_BR/LC_MESSAGES/mutt.mo
/usr/share/locale/ja/LC_MESSAGES/mutt.mo
/usr/share/locale/bg/LC_MESSAGES/mutt.mo
/usr/share/locale/eu/LC_MESSAGES/mutt.mo
/usr/share/locale/eo/LC_MESSAGES/mutt.mo
/usr/share/locale/ga/LC_MESSAGES/mutt.mo
/usr/share/locale/et/LC_MESSAGES/mutt.mo
/usr/share/locale/cs/LC_MESSAGES/mutt.mo
/usr/share/locale/ca/LC_MESSAGES/mutt.mo
/usr/share/locale/uk/LC_MESSAGES/mutt.mo
/usr/lib/mutt
/usr/lib/mutt/debian-ldap-query
/usr/lib/mutt/source-muttrc.d
/usr/lib/mutt/pgpring
/usr/lib/mutt/pgpewrap
/usr/lib/mutt/mailto-mutt
/usr/lib/mutt/mailspell
/usr/lib/mime/packages/mutt
